version: '3'
services:
  backend:
    build: ./server/
    ports:
      - 9999:9999
    container_name: backend
    env_file:
      - ./server/.env
    volumes:
      - ./server/:/server/

  frontend:
    build: ./client/
    ports:
      - 3000:3000
    depends_on:
      - backend
    container_name: frontend
    volumes:
      - ./client/:/client/